input('Please enter the followinng:')
adjective=input('ajective:')
animal=input('animal:')
verb_one=input('verb:')
exclamation=input('exclamation:')
verb_two=input('verb:')
verb_three=input('verb:')
verb_four_plus_ing=input('verb ending with ing:')
print()
print('Your story is:\n')
print('The other day, i was really in big trouble. It all started when i saw a very')
print(adjective, animal, verb_one + ' ' + 'down the hallway.' + f'{exclamation.capitalize()}!' + ' i yelled.')
print('But all i could think to do was to ' + verb_two + ' over and over.' + ' Miraculosly,')
print('that caused it to stop, but not before it tried to ' + verb_three)
print('right in front of my family.')
#Showed creativity in this last sentence
print('On one faithful day, i met a childhood friend at Massachusetts Institute of Technology and to my suprise,')
print('he had a masters degree in dish' + ' ' + verb_four_plus_ing)