child_meal_child_drink=float(input('What is the price of a child\'s meal and drink? '))
adult_meal_adult_drink=float(input('What is the price of an adult\'s meal and drink? '))
num_of_children=int(input('How many children are there? '))
num_of_adult=int(input('How many adults are there? '))
sales_tax_rate=float(input('What is the sales tax rate? '))
print()
meal_subtotal=((child_meal_child_drink * num_of_children) + (adult_meal_adult_drink * num_of_adult))
print(f'Meal subtotal:${meal_subtotal:.2f}')
sales_tax=(meal_subtotal * sales_tax_rate/100)
print(f'Sales Tax:${sales_tax}')
meal_totalprice=(meal_subtotal + sales_tax)
print(f'Meal total:${meal_totalprice}')
print()
payment_amount=float(input('Kindly enter a payment amount:'))
change=(payment_amount - meal_totalprice)
print(f'Change:${change:.2f}')